name: Chrome CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove default Chrome
        run: sudo apt-get purge google-chrome-stable -y || true

      - name: Install Chrome v137
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          google-chrome --version

      - name: Install ChromeDriver v137
        run: |
          LATEST=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE_137)
          wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Run your tests
        run: |
          echo "Running tests..."
          # 你可以替换下面命令为自己的测试命令
          # npm ci
          # npm run test
