name: ChromeDriver CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Chrome Beta
        uses: browser-actions/setup-chrome@latest
        with:
          channel: beta

      - name: Install ChromeDriver manually for Chrome 137 beta
        run: |
          # 下载匹配 beta 版 Chrome 的驱动（请确认是137开头的版本）
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/137.0.7225.0/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify ChromeDriver version
        run: chromedriver --version
