name: NodeSeek-Daily

on:
  push:
    branches:
      - main
  #schedule:
   #   - cron: '15 23 * * *' # 每天 UTC 23:15（北京时间 07:15）
  workflow_dispatch: # 支持手动触发

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: Clean cache
        run: |
          rm -rf ~/.cache/pip
          rm -rf ~/.cache/undetected-chromedriver

      - name: Add Google Chrome repository and install Chrome
        run: |
          sudo apt-get update
          # 列出当前环境中已安装的 Chrome/Chromium
          echo "Checking for existing Chrome/Chromium installations..."
          dpkg -l | grep -E 'chromium|google-chrome' || echo "No Chrome/Chromium found"
          # 彻底移除所有 Chrome 和 Chromium 相关包
          sudo apt-get purge -y chromium-browser chromium-chromedriver google-chrome-stable google-chrome-beta google-chrome-unstable || true
          sudo apt-get autoremove -y --purge
          sudo rm -rf /etc/apt/sources.list.d/*chrome*
          # 安装依赖
          sudo apt-get install -y wget gnupg ca-certificates
          # 添加 Google Chrome 存储库
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          # 强制安装最新稳定版 Chrome
          sudo apt-get install -y --reinstall google-chrome-stable
          echo "Chrome version after installation:"
          google-chrome --version || echo "Chrome installation failed"
          # 查找 Chrome 可执行文件路径
          echo "Chrome binary path:"
          which google-chrome || echo "Chrome binary not found"
          # 安装 Xvfb 支持无头模式
          sudo apt-get install -y xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall undetected-chromedriver==3.5.5
          pip install -r requirements.txt

      - name: Run NodeSeek script
        env:
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          NS_RANDOM: ${{ secrets.NS_RANDOM }}
          HEADLESS: "true"
        run: |
          xvfb-run -a python nodeseek_daily.py
