name: NodeSeek-Daily

on:
  push:
    branches:
      - main
  #schedule:
   # - cron: '0 00 * * *' # 每天 UTC 16:00（北京时间 08:00）
  workflow_dispatch: # 支持手动触发

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: Clean cache
        run: |
          rm -rf ~/.cache/pip
          rm -rf ~/.cache/undetected-chromedriver

      - name: Install Chrome 137
        run: |
          sudo apt-get update
          sudo apt-get purge chromium-browser chromium-chromedriver -y
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_137.0.7151.41-1_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_137.0.7151.41-1_amd64.deb
          echo "Chrome version:"
          google-chrome --version
          # 安装 Xvfb 支持无头模式
          sudo apt-get install -y xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall undetected-chromedriver==3.5.5  # 强制安装支持 Chrome 137 的版本
          pip install -r requirements.txt

      - name: Run NodeSeek script
        env:
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          NS_RANDOM: ${{ secrets.NS_RANDOM }}
          HEADLESS: "true"
        run: |
          # 启动 Xvfb 以支持无头模式
          xvfb-run -a python nodeseek_daily.py
